fixed domain prices displaying by adding Money.php class
hiqdev/hipanel-site pull request #26
Opened 2019-08-13 09:49 UTC by strorch

added domain searching by tariff plans 
added Money.php class to displaying domains and prices in grid

2019-08-13 10:02 UTC, hiqsol approved these changes

2019-08-13 10:10 UTC, SilverFire requested changes

2019-08-13 10:10 UTC, SilverFire commented on src/controllers/SiteController.php
> +        $plans = Yii::$app->cache->getOrSet('PlansGetAvailable', function () {
Запрос зависит от `SiteHelper::getSeller()`, значит сам `SiteHelper::getSeller()` должен быть включён в ключ кеширования

2019-08-13 11:27 UTC, tafid approved these changes

2019-08-19 08:43 UTC, SilverFire approved these changes

2019-08-19 08:43 UTC, merged